### ISSUE TITLE
`flycheck-aspell--handle-and` errors on curly quotes

### ISSUE THREAD

**Issue by zabe40** [leotaku/flycheck-aspell#14]
When checking a line with a curly quote (for example U+2019 `’` or U+201D `”`) the call to `string-match` in `flycheck-aspell--handle-and` doesn't match the curly quotes because it checks for the `word` character class rather than the `word` syntax. 

Changing `wordchar` to `(syntax word)` in the call to `rx` fixes this issue.

This issue also occurs in `flymake-aspell--handle-and`, `flycheck-aspell--handle-hash`, and `flymake-aspell--handle-hash`, and has the same fix.

Additionally, I think it might be worth opening a bug upstream since the elisp manual and the docstring of `rx` don't make the difference between `(rx word)` and `(rx (syntax word))` clear at all.

**Comment by leotaku** [comment]
I can not confirm this behavior with my version of Emacs.

```emacs-lisp
(string-match (rx (syntax word)) "’”")
;; => nil
(string-match (rx wordchar) "’”")
;; => nil
```

But I can see that the current behavior of only matching word characters is incorrect. It is entirely legal for Aspell-recognized words to contain apostrophes, or really any Unicode character except for SPACE, I suppose. I think I will swap the `(+ wordchar)` with `(+? anything)` and that should solve this and similar issues.
