### ISSUE TITLE
Describe how to deal with different languages

### ISSUE THREAD

**Issue by Kaligule** [leotaku/flycheck-aspell#16]
Aspell can be called with a language flag (`aspell` --lang=de`) to tell it what language to look for.
It would be great if I could somehow tell flycheck-aspell which language to use in a given buffer.

I think aspell defaults to the current locale setting, but that might not be the right thing for each buffer.

**Comment by Kaligule** [comment]
I found that running `ispell-change-dictionary` will work.
I still think that there should be a hint about it in the Readme.

This setup works fine for me, currently:

```emacs-lisp
(defun spell-german () (ispell-change-dictionary "de_DE"))
(defun spell-american () (ispell-change-dictionary "en_US"))

(add-hook 'org-mode-hook 'spell-german)
(add-hook 'prog-mode-hook 'spell-american)                                                          -
(add-hook 'text-mode-hook 'spell-american)
```

**Comment by leotaku** [comment]
It is already mentioned in the separate READMEs for `flymake-aspell` and `flycheck-aspell` that the language is derived from the settings for `ispell`. 

> The dictionary the checkers use is determined by the values of ispell-local-dictionary or, if the former variable is unset, ispell-dictionary.

But I agree that the layout of the documentation is currently somewhat confusing, I will look into restructuring it.

**Comment by Kaligule** [comment]
Thank you. I didn't see that when I was looking for it.

At least for me it would have helped when the word "language" would be anywhere near that sentence. because I did search for that.
