### ISSUE TITLE
Quelpa error, "Package lacks a file header"

### ISSUE THREAD

**Issue by xiangsheng** [leotaku/flycheck-aspell#3]
When installing the package with quelpa, I meet the error "Package lacks a file header". It seems that a copyright line is expected. 

For a reference, [https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html](url)

**Comment by leotaku** [comment]
Has this been resolved now?

Sorry for not responding sooner, I was on vacation and must have accidentally dismissed the notification.

**Comment by xiangsheng** [comment]
Yes, I can install the package properly now, nice job!
