### ISSUE TITLE
Args out of range processing markdown

### ISSUE THREAD

**Issue by Lenbok** [leotaku/flycheck-aspell#4]
Thanks for putting together this nice interface to allow spell checking with flycheck!

I edit a bunch of markdown documents, and hooked in your existing checker via:
```
   (add-to-list 'flycheck-checkers 'markdown-aspell-dynamic)
```
It mostly works fine, but I noticed that sometimes it gets the wrong positions for misspelt words.

Now I'm on ubuntu 20.04, it uses a version of aspell that has built-in support for markdown, so I thought using that might fix the problem....

```
 (flycheck-aspell-define-checker "new-markdown" "Markdown using aspell markdown filter"
   ("--add-filter" "url" "--add-filter" "markdown") (markdown-mode))
 (add-to-list 'flycheck-checkers 'new-markdown-aspell-dynamic)
```

However, when I use it, I get an error message like:
```
Error from syntax checker new-markdown-aspell-dynamic: Args out of range: "    mkdir ./venv", 79, nil
```
(where "    mkdir ./venv" is the entire contents of a line in the markdown file, but it is inside a preformatted block being ignored by aspell, the actual occurrence of "venv" being complained about is further down, on a much longer line). I don't think the inherent problem here is the new aspell mode, it looks like the spellcheck result parsing is getting out of sync with where the actual occurrences are.

**Comment by leotaku** [comment]
The Aspell output parser for flycheck-aspell definitely deserves a rewrite. It is kind of hard for me to reproduce your problem, but I will refactor the parser to be more robust, which should, in theory, resolve this issue.

**Comment by Lenbok** [comment]
The following content reproduces it for me using your standard markdown-aspell-dynamic (save into foo.md or something)

```
Here's some text with perfectly fine spelling.

    http://cmd/something/else

Now we are going to put some text that uses cmd further on the line.
```

The initial occurrence of "cmd" is ignored from spellcheck due to the url filter, but causes the error during parsing.

**Comment by leotaku** [comment]
Thanks for the reproducible example. I can confirm that your example used to fail but no longer does so with the newly-rewritten parser. The fix should land on master in a few minutes.

**Comment by leotaku** [comment]
The issue should now be fixed on the master branch. I'd be grateful if you could test out the new version and report whether my changes have also fixed the problem on your side.

**Comment by Lenbok** [comment]
I updated and now it pegs the CPU on the following example (still with the built-in `markdown-aspell-dynamic`):

```
# bar

[![Python 3.8](https://img.shields.io/badge/python-3.8-blue.svg)](https://www.python.org/downloads/release/python-382/)
[![Code style: black](https://img.shields.io/badge/code%20style-black-000000.svg)](https://github.com/ambv/black)


## Development setup

Clone from GitHub:

    git clone -b develop git@github.com:foo/bar.git

Create a virtual environment for the project:

    cd bar
    mkdir ./venv
    ${HOME}/.pyenv/versions/3.8.2/bin/python -m venv venv/bar
    source ./venv/bar/bin/activate

Do post-clone setup (commit hook setup, installation of python packages into venv, etc):

    make init

Lightweight make targets for testing:

    make lint
    make mypy
    make pytest

Less lightweight make targets with extra code checks:
```

**Comment by leotaku** [comment]
Your example does not cause any unusual CPU usage on my machine. However, I was able to confirm a noticeable performance regression on larger files. Again, this should now be fixed on the master branch and I would appreciate your feedback.

**Comment by Lenbok** [comment]
Hi, I got your latest two commits and everything is working swimmingly (including the new markup checker I defined in the initial description, which nicely ignores block quotes etc). Thanks!

**Comment by leotaku** [comment]
Great to hear! Just FYI, I have now also changed the default Markdown spell checker to use the corresponding new filter. The GNU Aspell version that added it is almost a year old now, so it should hopefully not cause too much breakage.
