### ISSUE TITLE
submit package to melpa

### ISSUE THREAD

**Issue by tychoish** [leotaku/flycheck-aspell#7]
Would you be opposed to submitting this package (or packages?) to melpa? 

I'm willing to submit the package on your behalf.

**Comment by leotaku** [comment]
I am not at all opposed to it, but I imagine it could be hard to convince the maintainers to accept the project in it's current state.

As of right now, this repository contains both the code for a flycheck and a flymake backend. The MELPA guide specifically mentions that all packages should live in their own repository.

It may be a good idea to split the repository anyways, but I'm a bit short on time and not particularly interested in keeping two separate projects in sync. (sorry)

If you think the packages would get accepted in their current "shared repo" state, I'll gladly take you up on your offer to submit them to MELPA for me. Thanks!

**Comment by tychoish** [comment]
no worries! It's worth a shot. It's not as if the current state is particularly out of hand.

**Comment by leotaku** [comment]
I see your PR against MELPA has been merged, which should resolve this issue thread. I will update the README to reflect that the packages can now be installed from MELPA.

Thanks again for your help in getting my package into MELPA!
